spring.application.name=batch
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
# Enable the web viewer for the database
spring.h2.console.enabled=true
# Use this to see exactly what SQL Spring is running in the background
#logging.level.org.springframework.jdbc.core=DEBUG
# Tell Spring to run our schema.sql file on startup
spring.sql.init.mode=always
# Add this line to disable the auto-run feature
spring.batch.job.enabled=false